# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml     

trigger:
- dev

pool:
  vmImage: ubuntu-latest

name: $(Date:yyyyMMdd)$(Rev:.r)
stages:

- stage: Build
  jobs:   
  - job: "B2"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job j1' 
  
- stage: Test
  dependsOn: [Build]
  jobs:
  - job: "Delay"
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
  - job: "Te1"
    displayName: Wait For External Validation
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job TE1'

- stage: Prod
  dependsOn: [Test]
  jobs:
  - job: "P3"
    pool: server
    steps:  
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'empbkaranam7-eshwarmolugu-ServiceNow DevOps Service Connection'
        UpstreamJob: 'Delay'
