trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "One"
    pool: server
    steps:   
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'ChangeControl_con'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
