trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "FirstCR"
    pool: server
    steps:   
    - task: InvokeRESTAPI@1 
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'eshwar_azure_amar_instance'
        method: 'POST'
        body: |
             {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
                }
        waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
