trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Test
  jobs:
  - job: 'Four'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'master'))
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'empmolugu'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'
  - job: 'django_basic'
  pool:
    vmImage: 'Ubuntu-16.04'
    strategy:
    matrix:
      Python36_Django213:
        python.version: '3.6'
        django.version: '2.1.3'
      Python37_Django213:
        python.version: '3.7'
        django.version: '2.1.3'
      Python37_Django214:
        python.version: '3.7'
        django.version: '2.1.4'
    maxParallel: 3