trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Test
  jobs:
  - job: 'Four'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'empmolugu'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
         python.version: '3.7'
      maxParallel: 2
  - job: "Two"
    steps:
    - task: Bash@3
      
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world '
          echo $(build.sourceBranchName)
      
 