trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "j1"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job j1' 
  
- stage: Test
  jobs:
  - job: 'j2'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Job j2 '
 
- stage: Deploy
  jobs:
  - job: "j3"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Job j3 ' 
  