trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Test
  jobs:
  - job: 'Four'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'empmolugu'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'
- stage: Deploy
  jobs:
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
         python.version: '3.7'
      maxParallel: 2
      
- stage: Prod
  jobs:
  - job: 'django_basic'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python36_Django213:
          python.version: '3.6'
          django.version: '2.1.3'
        Python37_Django213:
          python.version: '3.7'
          django.version: '2.1.3'
        Python37_Django214:
          python.version: '3.7'
          django.version: '2.1.4'
      maxParallel: 3