trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "One"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job ' 
  - job: "Two"
    steps:
    - task: Bash@3
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'master'))
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world '
          echo $(build.sourceBranchName)
- stage: Test
  jobs:
  - job: 'Three'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world'

  - job: 'Four'
    dependsOn: 'Three'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'empmolugu'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'