# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: workItemsFilePath
  value: "Thisfile"
- name: pipelineTag
  value: release
- name: serviceConnection
  value: AnansiServiceNow

stages:
  - stage: CreateChange
    jobs:
      - job: 'CreateChangeRequest'
        displayName: 'CreateChangeRequest'
        pool: server        
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            inputs:
              connectedServiceName: 'rohit111'
              isToken: false


