trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "B1"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job j1' 
  - job: "B2"
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'First job j1' 
  
- stage: Test
  dependsOn: []
  jobs:
  - job: 'T1'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Job j2 '
  - job: 'T2'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Job j2 '

  