trigger:
- master
pool:
  vmImage: ubuntu-latest
stages:
- stage: __default
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: -Xmx3072m
        javaHomeOption: JDKVersion
        jdkVersionOption: 1.8
        jdkArchitectureOption: x64
        publishJUnitResults: false
        goals: compile
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: Devops Demo
        artifactsPayload: >
          {
             "artifacts": [
                {
                   "name": "Corpsite",
                   "version": "1.$(Build.BuildId)",
                   "semanticVersion": "1.$(Build.BuildId).0",
                   "repositoryName": "CorpsiteReleases"
                }
             ]
          }
  - job: TestJob
    dependsOn:
    - BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        goals: verify
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: TestJob
        javaHomeOption: JDKVersion
        mavenVersionOption: Default
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
  - job: PackageJob
    dependsOn:
    - TestJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: -Xmx3072m
        javaHomeOption: JDKVersion
        jdkVersionOption: 1.8
        jdkArchitectureOption: x64
        publishJUnitResults: false
        goals: package
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/target/globex-web.war
        artifactName: Globex-web
  - job: ProdJob
    dependsOn:
    - PackageJob
    pool:
      name: server
    steps:
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: Devops Demo
        UpstreamJob: PackageJob

